#! /bin/bash -o errexit -o pipefail

tmp_dir='/tmp/book'
github_io_dir="$(echo ~/ctm.github.io/docs/players_manual)"

function add_and_push() {
    git add -A
    if ! git diff-index --quiet HEAD --; then
        git commit -m '' --allow-empty-message
        git push
    fi
}

rm -rf "$tmp_dir"
git worktree add -f "$tmp_dir" gh-pages
mdbook build
rm -rf "$tmp_dir/*"
cp -rp book/* "$tmp_dir/"
( cd "$tmp_dir" && add_and_push )
( cd "$github_io_dir" && git pull && cd .. && add_and_push )
